### ISSUE TITLE
[help wanted] error on parsing a valid TOML configuration

### ISSUE THREAD

**Issue by melopee** [aatxe/irc#101]
Hello,  
I'm getting the following error:
```
Error(Io(Error { repr: Custom(Custom { kind: InvalidInput, error: StringError("Failed to decode TOML configuration file.") }) }), State { next_error: Some(Error { inner: ErrorInner { kind: Custom, line: None, col: 0, message: "invalid type: sequence, expected a string", key: ["options", "array"] } }), backtrace: None })', /checkout/src/libcore/result.rs:906:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

when I launch the configuration
```toml
nickname = "pine"
alt_nicks = ["apple","pen"]
server = "chat.freenode.net"
use_ssl = true
port = 6697
encoding = "UTF-8"
channels = ["broda","brode"]

[options]
string = "imastring"
array = ["i","m","a","array"]
```

with the method `IrcServer::new()`.

But with this one:
```toml
nickname = "pine"
alt_nicks = ["apple","pen"]
server = "chat.freenode.net"
use_ssl = true
port = 6697
encoding = "UTF-8"
channels = ["broda","brode"]

[options]
string = "imastring"
array = "imnotanarray"
```

there's no problems.

This crate is using the crate `toml`; so I've tested if it was a problem of `toml` rather than `irc`, with this program:
```rust
extern crate toml;
use toml::Value;
use std::fs::File;
use std::io::Read;
use std::io;
use std::env;
fn main() {
    let args = env::args().collect::<Vec<_>>();
    let data = load(&args[1]).unwrap();
    let value = data.parse::<Value>().unwrap();
    println!("{}",value);
    println!("{:?}",value);
}

fn load(x: &str) -> Result<String, io::Error> {
    let mut s = String::new();
    File::open(x)?.read_to_string(&mut s)?;
    Ok(s)
}
```

And this program works for both config expressed above.  
I was so wanting to know if it's really a bug in the use of `toml` by `irc`, or if there's any mistakes in my approach.

Thank you!
